### ISSUE TITLE
Converting Gulpfile to ESM generates errors after updating gulp-imagemin

### ISSUE THREAD

**Issue by stefanobartoletti** [stefanobartoletti/bricks#92]
### Describe the bug

I'm in the process of updating `gulpfile.js` from CommonJS to ESM, to support some updated plugins that come only in this format (mainly `gulp-imagemin`). 
The main change is related to the new `import` syntax instead of `require`: so, in example, `const autoprefixer = require('gulp-autoprefixer');` is now `import autoprefixer from 'gulp-autoprefixer';`.

The Gulpfile was renamed to `gulpfile.esm.js` and I have installed the `esm` NPM package, following the [instructions on the Gulp docs](https://gulpjs.com/docs/en/getting-started/javascript-and-gulpfiles/#transpilation).

The updated gulpfile is available here = https://github.com/stefanobartoletti/bricks/blob/gulp-esm/gulpfile.esm.js

After this conversion everything works well, all the tasks do what they are supposed to do, **until I try to update `gulp-imagemin` from `v7.1.0` to `v8.0.0`**.

After trying to update it, the follwing errors appear after trying to run the scripts:

```bash
% yarn
yarn install v1.22.11
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ gulp default
[15:17:01] Requiring external module esm
TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:34:9)
    at eval (eval at <anonymous> (/Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/gulp-cli/lib/shared/require-or-import.js:10:15), <anonymous>:3:1)
    at requireOrImport (/Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/gulp-cli/lib/shared/require-or-import.js:24:7)
    at execute (/Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
    at Liftoff.handleArguments (/Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/gulp-cli/index.js:211:24)
    at Liftoff.execute (/Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/liftoff/index.js:201:12)
    at module.exports (/Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/liftoff/index.js:191:5)
    at /Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/liftoff/index.js:149:9
    at /Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/v8flags/index.js:162:14 {
  code: 'ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

and

```bash
% yarn build
yarn run v1.22.11
$ gulp build
[15:20:53] Requiring external module esm
TypeError: Invalid host defined options
    at eval (eval at <anonymous> (/Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/gulp-cli/lib/shared/require-or-import.js:10:15), <anonymous>:3:1)
    at requireOrImport (/Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/gulp-cli/lib/shared/require-or-import.js:24:7)
    at execute (/Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
    at Liftoff.handleArguments (/Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/gulp-cli/index.js:211:24)
    at Liftoff.execute (/Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/liftoff/index.js:201:12)
    at module.exports (/Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/liftoff/index.js:191:5)
    at /Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/liftoff/index.js:149:9
    at /Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/v8flags/index.js:162:14
    at /Users/stefanobartoletti/Sviluppo/Personali/bricklayer/bricks/node_modules/v8flags/index.js:41:14
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps To Reproduce

1. Clone this repository: `git clone https://github.com/stefanobartoletti/bricks.git`
2. Switch to `gulp-esm` branch, where the update of the Gulp configuration is developed: `git checkout gulp-esm`
3. Install dependencies: `yarn`
4. Test tasks to confirm that everything goes fine: `yarn dev`, `yarn build`, `yarn watch` (no errors are expected until now).
5. Upgrade `gulp-imagemin` to `v8.0.0`: `yarn upgrade --latest gulp-imagemin`
6. Run `yarn dev`, the previous errors appear, preventing the task to complete successfully.

### Summary
After converting gulpfile to ESM, updating `gulp-imagemin` to `v8.0.0` generates some errors about 
- `TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.`
- `TypeError: Invalid host defined options`

Some help is welcome with this issue, as I am unable to figure out myself how to solve it.

**Comment by stefanobartoletti** [comment]
I was able to solve this by reverting `gulpfile.esm.js` to `gulpfile.js`, and declaring `"type": "module"` inside `package.json`.

**Comment by Jobayer-ak** [comment]
same problem i am facing but couldn't find any solution...don't know how i can fix it.

**Comment by stefanobartoletti** [comment]
Hi, If you need help please open a new issue with a detailed description

**Comment by billyromano** [comment]
> I was able to solve this by reverting `gulpfile.esm.js` to `gulpfile.js`, and declaring `"type": "module"` inside `package.json`.

When I do this simple change, I get the following errors showing up instead:
```
% npm run test
> gulp test --dev

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users/XXXXXX/_work/_git/PROJECT/gulpfile.js' is not supported resolving ES modules imported from /Users/XXXXXX/_work/_git/PROJECT/node_modules/gulp-cli/lib/shared/require-or-import.js
Did you mean to import /Users/XXXXXX/_work/_git/PROJECT/gulpfile.js/index.js?
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:314:17)
    at moduleResolve (internal/modules/esm/resolve.js:776:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at Loader.import (internal/modules/esm/loader.js:177:28)
    at importModuleDynamically (internal/modules/cjs/loader.js:1028:27)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at eval (eval at <anonymous> (/Users/XXXXXX/_work/_git/PROJECT/node_modules/gulp-cli/lib/shared/require-or-import.js:10:15), <anonymous>:3:1) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///Users/XXXXXX/_work/_git/PROJECT/_git/chase_abe_education/gulpfile.js'
}
```

Any ideas what might be causing this error?

I'm also using the code splitting technique for the `gulpfile.esm.js` file: `gulpfile.esm.js/index.js`

Here's my sample `index.js` file to test (inside the `gulpfile.js` folder–following your example to rename it):
```
import gulp      from "gulp";
import rimraf    from "rimraf";

export const test = gulp
    .series((done) => {
        rimraf("./dist", done);
    })(done);

```
